# Generated by Django 3.2.4 on 2021-07-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_remove_tag_post'),
        ('posts', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
