# Generated by Django 3.2.4 on 2021-07-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postabout_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postabout',
            name='slug',
        ),
    ]
