# Generated by Django 3.2.4 on 2021-07-14 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_postabout_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postabout',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
