# Generated by Django 3.2.4 on 2021-09-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postabout_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_9',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
