# Generated by Django 3.2.4 on 2021-07-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
