# Generated by Django 3.2.4 on 2021-09-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_postabout_description_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_tag',
            field=models.TextField(blank=True, help_text='Максимальная длина 200 символов.', max_length=200, verbose_name='тег description'),
        ),
        migrations.AlterField(
            model_name='postabout',
            name='description_tag',
            field=models.TextField(blank=True, help_text='Максимальная длина 200 символов.', max_length=200, verbose_name='тег description'),
        ),
    ]
