# Generated by Django 3.2.4 on 2023-02-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wysiwyg_img', '0001_initial'),
        ('posts', '0017_auto_20210913_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('baseimagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wysiwyg_img.baseimagemodel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            bases=('wysiwyg_img.baseimagemodel',),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
