services:
  app:
    build: ./app
    volumes:
     - static_data:/app/static
    depends_on:
      db:
      condition: service_healthy
    restart: always
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/app/static
    restart: always

  db:
    image: postgres:15.12
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    
volumes:
  static_data:
  postgres_data: