# Generated by Django 3.2.4 on 2021-08-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_username', models.CharField(max_length=40, verbose_name='Представьтесь:')),
                ('text', models.TextField(max_length=700, verbose_name='Текст:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GuestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='Имя администратора:')),
                ('text', models.TextField(max_length=700, verbose_name='Текст:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('guest_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guestroom.guestpost')),
            ],
        ),
    ]
