# Generated by Django 3.2.4 on 2021-07-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestPostModel',
            new_name='GuestPost',
        ),
    ]
