# Generated by Django 3.2.4 on 2021-09-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestcomment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии к сообщениям'},
        ),
        migrations.AlterModelOptions(
            name='guestpost',
            options={'ordering': ['-created'], 'verbose_name': 'гостевое сообщение', 'verbose_name_plural': 'гостевые сообщения'},
        ),
    ]
