# Generated by Django 3.2.4 on 2021-09-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0002_auto_20210901_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcomment',
            name='username',
            field=models.CharField(default='@YuriyCherniy', max_length=40, verbose_name='Имя администратора:'),
        ),
        migrations.AlterField(
            model_name='guestpost',
            name='text',
            field=models.TextField(help_text='This site is protected by reCAPTCHA and the Google         <a href="https://policies.google.com/privacy">Privacy Policy</a> and         <a href="https://policies.google.com/terms">Terms of Service</a> apply.', max_length=700, verbose_name='Текст:'),
        ),
    ]
