# Generated by Django 3.2.4 on 2021-07-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0002_rename_guestpostmodel_guestpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestpost',
            old_name='anonymous_user_name',
            new_name='anonymous_username',
        ),
    ]
