# Generated by Django 3.2.4 on 2021-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0003_auto_20210904_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGuestPostCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
            ],
        ),
    ]
