# Generated by Django 3.2.4 on 2021-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0003_rename_anonymous_user_name_guestpost_anonymous_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpost',
            name='anonymous_username',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='guestpost',
            name='text',
            field=models.TextField(max_length=700),
        ),
    ]
