# Generated by Django 3.2.4 on 2021-09-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    def set_counter(apps, schema_editor):
        counter = apps.get_model('guestroom', 'NewGuestPostCounter')
        counter.objects.create(counter=0)

    dependencies = [
        ('guestroom', '0004_newguestpostcounter'),
    ]

    operations = [
        migrations.RunPython(set_counter)
    ]
