# Generated by Django 3.2.4 on 2021-07-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0004_auto_20210717_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpost',
            name='anonymous_username',
            field=models.CharField(max_length=40, verbose_name='Представьтесь:'),
        ),
        migrations.AlterField(
            model_name='guestpost',
            name='text',
            field=models.TextField(max_length=700, verbose_name='Текст:'),
        ),
        migrations.CreateModel(
            name='GuestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('text', models.TextField(max_length=700)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('guest_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guestroom.guestpost')),
            ],
        ),
    ]
