# Generated by Django 3.2.4 on 2021-09-10 12:51

from django.db import migrations


def set_counter(apps, schema_editor):
    model = apps.get_model('guestroom', 'NewGuestPostCounterModel')
    model.objects.create(counter=0)


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0004_newguestpostcountermodel'),
    ]

    operations = [
        migrations.RunPython(set_counter)
    ]
