# Generated by Django 3.2.4 on 2021-07-21 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0005_auto_20210717_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='guestcomment',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='Имя администратора:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestcomment',
            name='text',
            field=models.TextField(max_length=700, verbose_name='Текст:'),
        ),
    ]
