# Generated by Django 3.2.4 on 2021-09-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0005_auto_20210910_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcomment',
            name='username',
            field=models.CharField(default='Алла (админ)', max_length=40, verbose_name='Имя администратора:'),
        ),
    ]
