# Generated by Django 3.2.4 on 2021-07-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0006_auto_20210721_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpost',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
