# Generated by Django 3.2.4 on 2021-07-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestroom', '0007_guestpost_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestpost',
            name='is_new',
        ),
    ]
