# Generated by Django 3.2.4 on 2021-07-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
    ]
