# Generated by Django 3.2.4 on 2021-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
