# Generated by Django 3.2.4 on 2021-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_description_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_tag',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
