# Generated by Django 3.2.4 on 2021-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_description_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postabout',
            name='description_tag',
            field=models.TextField(blank=True, help_text='Максимальнае длина 200 символов.', max_length=200, verbose_name='тег description'),
        ),
    ]
